---
## Nagios Variables
auto_register_client: true
nagios_host: nagios.sharedservices.aws.internal
server_template_name: "SMTP_Server"
nrpe_allowed_hosts:
  - "127.0.0.1"
  - "10.44.12.0/24"
  - "10.44.13.0/24"
  - "10.44.14.0/24"
nrpe_plugin_packages:
  - nagios-plugins-nrpe
  - nagios-plugins
  - nagios-plugins-disk
nrpe_config: 
  dont_blame_nrpe: 1
nrpe_command:
  check_disk:
    script: check_disk
    option: $ARG1$
  check_load:
    script: check_load
    option: $ARG1$
  check_sshd:
    sudo: true
    script: check_service.sh
    option: $ARG1$
  check_postfix:
    sudo: true
    script: check_service.sh
    option: $ARG1$
  check_syslogd:
    sudo: true
    script: check_service.sh
    option: $ARG1$
  check_users:
    script: check_users
    option: $ARG1$