---
- name: Copy amazon-cloudwatch-agent.json template
  copy:
    src: ./ansible/template/amazon-cloudwatch-agent.json
    dest: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent.json
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Tell the agent to use the new config 
  shell: sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent.json

- name: Stop Cloudwatch agent
  shell: amazon-cloudwatch-agent-ctl -a stop

- name: Start Cloudwatch agent
  shell: amazon-cloudwatch-agent-ctl -a start

- name: Status Cloudwatch agent
  shell: amazon-cloudwatch-agent-ctl -a status
