#!/bin/sh
# Localize these.
INSPECT_DIR=/var/spool/filter
SENDMAIL=/usr/sbin/sendmail

# Define our company address lists
disclaimer_addresses_ch=/etc/postfix/disclaimer_addresses_ch
disclaimer_addresses_ipo=/etc/postfix/disclaimer_addresses_ipo

# Exit codes from <sysexits.h>
EX_TEMPFAIL=75
EX_UNAVAILABLE=69

# Clean up when done or when aborting.
trap "rm -f in.$$" 0 1 2 3 15

# Start processing.
cd $INSPECT_DIR || { echo $INSPECT_DIR does not exist; exit
$EX_TEMPFAIL; }

#echo in.$$ > /var/tmp/disclaimer.log

cat >in.$$ || { echo Cannot save mail to file; exit $EX_TEMPFAIL; }

# Obtain From address domain
from_address=`grep -m 1 "^From:" in.$$ | cut -f2 -d "@" | cut -d ">" -f1`

if [ `grep -wi ${from_address} ${disclaimer_addresses_ch}` ]; then
/usr/bin/altermime --input=in.$$ \
                   --disclaimer=/etc/postfix/disclaimer_ch.txt \
                   --disclaimer-html=/etc/postfix/disclaimer_ch.txt || \
                    { echo Message content rejected; exit $EX_UNAVAILABLE; }
fi

if [ `grep -wi ${from_address} ${disclaimer_addresses_ipo}` ]; then
/usr/bin/altermime --input=in.$$ \
                   --disclaimer=/etc/postfix/disclaimer_ipo.txt \
                   --disclaimer-html=/etc/postfix/disclaimer_ipo.txt || \
                    { echo Message content rejected; exit $EX_UNAVAILABLE; }
fi
$SENDMAIL "$@" <in.$$

exit $?