---  
- name: AMI Build
  hosts: smtp-outbound
  become: true
  gather_facts: yes
  #vars:
    #ansible_python_interpreter: /usr/local/bin/python3.6
  roles:
    - role: epel
    - role: email-server-config

